trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    useGlobalJson: true

- task: PowerShell@2
  displayName: Build
  inputs:
    filePath: '$(Build.SourcesDirectory)/build.ps1'

- publish: '$(Build.SourcesDirectory)/artifacts/DacPacBuilder.$(Build.BuildNumber).nupkg'
  artifact: DacPacBuilder
