trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    useGlobalJson: true

- task: PowerShell@2
  displayName: Build
  inputs:
    filePath: '$(Build.SourcesDirectory)/build.ps1'

- publish: '$(Build.SourcesDirectory)/artifacts/DacPacBuilder.$(Build.BuildNumber).nupkg'
  artifact: DacPacBuilder

- task: NuGetCommand@2  
  inputs:
    command: 'push'
    packagesToPush: '$(Build.SourcesDirectory)/artifacts/DacPacBuilder.$(Build.BuildNumber).nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'DacPacBuilder GitHub Nuget'
  
- task: NuGetCommand@2
  condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), startsWith(variables['Build.SourceBranch'], 'refs/heads/release/')))
  inputs:
    command: 'push'
    packagesToPush: '$(Build.SourcesDirectory)/artifacts/DacPacBuilder.$(Build.BuildNumber).nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'DacPacBuilder Nuget'

